accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profiles', views.ProfileTopListView.as_view(), name='profile_list'),
    path('<str:username>/', include([
         path(
             '',
             views.ProfileDetailView.as_view(),
             name='profile_detail'),
         path(
             'update',
             views.ProfileUpdateView.as_view(),
             name='profile_update'),
         path(
             'follow',
             views.ProfileFollowView.as_view(),
             name='profile_follow'),
         path(
             'followers',
             views.ProfileFollowersListView.as_view(),
             name='profile_followers_list'),
         path(
             'following',
             views.ProfileFollowingListView.as_view(),
             name='profile_following_list')]))
]

yawm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache
import notifications.urls
from ckeditor_uploader import views as ckeditor_uploader_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'inbox/notifications/',
        include(
            notifications.urls,
            namespace='notifications')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('auth/', include('allauth.urls')),

    path('ckeditor/', include([
        path(
            'upload/',
            login_required(ckeditor_uploader_views.upload),
            name='ckeditor_upload'
        ),
        path(
            'browse/',
            login_required(never_cache(ckeditor_uploader_views.browse)),
            name='ckeditor_browse'
        ),
    ])),
    path('', include('diaries.urls', namespace='diaries')),
    # re_path(r'^api/(?P<version>(v1|v2))/', include([
    path('api/v1/', include([
        path('diaries/', include('diaries.api.urls', namespace='diaries_api'))
    ])),

]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
from django.db import models
from django.db.models import Count, F
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse

from .utils import assign_default_image_to_profile
from core.utils import get_image_upload_path


class ProfileQuerySet(models.QuerySet):
    def with_diaries_followers_count(self):
        return self.annotate(
            written_diaries_count=Count('written_diaries', distinct=True),
            followers_count=Count('followers', distinct=True),
        )

    def top(self):
        qs = self.with_diaries_followers_count()
        qs = qs.annotate(
            interactions=F('written_diaries_count') + F('followers_count')
        ).order_by('-interactions')
        return qs


class Profile(models.Model):
    MALE = 'm'
    FEMALE = 'f'
    NOT_SPECIFIED = 'n'
    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (NOT_SPECIFIED, 'I prefer not to say')
    )

    name = models.CharField(
        help_text='If you don\'t provide one. your username will be used',
        max_length=63,
        blank=True
    )
    followers = models.ManyToManyField(
        'self',
        related_name='followed_profiles',
        symmetrical=False,
        blank=True
    )
    image = models.ImageField(
        upload_to=get_image_upload_path,
        null=True,
        blank=True
    )
    description = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text='Describe yourself in less than 255 character.'
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        default=NOT_SPECIFIED
    )

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='profile'
    )

    objects = ProfileQuerySet.as_manager()

    def __str__(self):
        return '{}'.format(self.name)

    def get_absolute_url(self):
        return reverse('accounts:profile_detail', args=[self.user.username])

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.user.username
        return super(Profile, self).save(*args, **kwargs)

    @property
    def visible_written_diaries_count(self):
        return self.written_diaries.filter(is_visible='all').count()


def create_profile(sender, instance, created, **kwargs):
    if created:
        new_profile = Profile(user=instance)
        new_profile = assign_default_image_to_profile(new_profile)
        new_profile.save()


post_save.connect(create_profile, sender=settings.AUTH_USER_MODEL)

accounts/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'image', 'gender', 'description')
        widgets = {
            'description': forms.Textarea()
        }

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import (
    View,
    DetailView,
    ListView,
    UpdateView
)
from notifications.signals import notify

from .forms import ProfileForm
from .models import Profile
from .utils import assign_default_image_to_profile


class ProfileListBaseView(LoginRequiredMixin, ListView):
    template_name = 'accounts/profile_list.html'
    model = Profile
    paginate_by = 12
    context_object_name = 'profiles'


class ProfileTopListView(ProfileListBaseView):

    extra_context = {'title': 'People worth following'}

    def get_queryset(self):
        return self.model.objects.top()


class ProfileFollowersListView(ProfileListBaseView):

    def get_context_data(self, *args, **kwargs):
        cx = super().get_context_data(*args, **kwargs)
        username = self.kwargs.get('username')
        cx['title'] = 'People that follow {}'.format(username)
        return cx

    def get_queryset(self):
        username = self.kwargs.get('username')
        profile = get_object_or_404(self.model, user__username=username)

        followers = profile.followers.all().with_diaries_followers_count()
        return followers


class ProfileFollowingListView(ProfileListBaseView):

    def get_context_data(self, *args, **kwargs):
        cx = super().get_context_data(*args, **kwargs)
        username = self.kwargs.get('username')
        cx['title'] = 'People {} follows'.format(username)
        return cx

    def get_queryset(self):
        username = self.kwargs.get('username')
        profile = get_object_or_404(self.model, user__username=username)

        followed_profiles = profile.followed_profiles.all()\
            .with_diaries_followers_count()

        return followed_profiles


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    slug_url_kwarg = 'username'
    template_name = 'accounts/profile_update.html'

    def get_object(self):
        obj = get_object_or_404(
            self.model,
            user__username=self.kwargs[self.slug_url_kwarg]
        )
        if not obj == self.request.user.profile:
            raise Http404
        return obj

    def form_valid(self, form):
        if not form['image'].data and not form.instance.image:
            form.instance = assign_default_image_to_profile(form.instance)
        return super().form_valid(form)


class ProfileDetailView(DetailView):
    template_name = 'accounts/profile_detail.html'
    slug_field = 'user__username'
    slug_url_kwarg = 'username'

    def get_object(self):
        obj = Profile.objects.with_diaries_followers_count().filter(
            user__username=self.kwargs[self.slug_url_kwarg]
        )
        if not obj:
            raise Http404
        return obj.first()

    def get_context_data(self, *args, **kwargs):
        cx = super().get_context_data(*args, **kwargs)
        cx['diaries'] = self.object.written_diaries.active(self.request.user)
        return cx


class ProfileFollowView(LoginRequiredMixin, View):
    def get(self, request, username):
        profile = get_object_or_404(Profile, user__username=username)
        return redirect(profile)

    def post(self, request, username):
        profile = get_object_or_404(Profile, user__username=username)
        current_profile = request.user.profile

        if profile != current_profile:
            if current_profile in profile.followers.all():
                profile.followers.remove(current_profile)
            else:
                profile.followers.add(current_profile)
                notify.send(
                    sender=current_profile,
                    recipient=profile.user,
                    verb='Started following you'
                )
            profile.save()
            return redirect(profile)
        return redirect(profile)

accounts/templates/accounts/base_accounts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}}{% endblock %}


{% block stylesheet %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{% static 'core/css/main.css' %}">
{% endblock %}

{% block body %}
	{{block.super}}
	<div class="container">
		{% block content %}{% endblock %}
	</div>
{% endblock %}

{% block javascript %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{% static 'core/css/main.css' %}">
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base_accounts.html' %}
{% load crispy_forms_tags %}
{% block title %}Login - {{block.super}}{% endblock %}

{% block stylesheet %}
	{{block.super}}
{% endblock %}

{% block content %}
	<h2>Login:</h2>
	<form method="post" action="{% url 'accounts:login' %}">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="login"  class="btn btn-block btn-success"/>
		<input type="hidden" name="next" value="{{ next }}" />
	</form>
{% endblock %}

{% block javascript %}
	{{block.super}}
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends 'accounts/base_accounts.html' %}
{% load thumbnail %}

{% block title %}{{ profile.name }} - {{block.super}}{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12 text-center">
		<img src="{% thumbnail profile.image '50x50' crop='90px' as img %}{{ img.url }}{% endthumbnail %}" class="img-fluid rounded-circle" style="height: 120px !important; width: 120px !important;">
		<h3>{{ profile.name }}</h3>
		{% if request.user.profile == profile %}
		<p>Diaries: {{ profile.written_diaries_count }}</p>
		{% else %}
		<p>Diaries: {{ profile.visible_written_diaries_count }}</p>
		{% endif %}		
		<p>Followers: {{ profile.followers_count }}</p>
	</div>
</div>
<div class="row">
	{% if request.user.is_authenticated %}
	<div class="col-md-12 text-center">
		<form method="post" action="{% url 'accounts:profile_follow' profile.user.username %}">
			{% csrf_token %}
				{% if request.user.profile != profile %}
					{% if request.user.profile in profile.followers.all %}
						<button class="btn btn-dark">Unfollow</button>
					{% else %}
						<button class="btn btn-success">Follow</button>
					{% endif %}
				{% endif %}
		</form>
	</div>
	<div class="col-md-12 text-center my-3">
		<a href="{% url 'accounts:profile_following_list' profile.user.username %}" class="btn btn-info">Following</a>
		<a href="{% url 'accounts:profile_followers_list' profile.user.username %}" class="btn btn-info">Followers</a>
	</div>
	{% endif %}
</div>
	{% include 'diaries/snippets/diary_list_snippet.html' with diaries=diaries %}
{% endblock %}

accounts/templates/accounts/profile_list.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}{{ title }} - {{block.super}}{% endblock %}

{% block content %}
	<h2>{{ title }}:</h2>
	{% include 'accounts/snippets/profile_list_snippet.html' with profiles=profiles %}
{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'accounts/base_accounts.html' %}

{% block title %}Update Profile - {{block.super}}{% endblock %}

{% block content %}
	<h2>Update Profile:</h2>
	<p>
		<a href="{% url 'account_change_password' %}">Change my password</a>
	</p>
	<form method="post" action="{% url 'accounts:profile_update' request.user.username %}" enctype="multipart/form-data">
		{% csrf_token %}
		{% include 'core/snippets/form_fields.html' with form=form %}
		<input type="submit" value="Update" class="btn btn-block btn-success" />
		<input type="hidden" name="next" value="{{ next }}" />
	</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base_accounts.html' %}
{% load crispy_forms_tags %}
{% block title %}Signup - {{block.super}}{% endblock %}

{% block stylesheet %}
	{{block.super}}
{% endblock %}

{% block content %}
	<h2>Signup:</h2>
	<form method="post" action="{% url 'accounts:signup' %}">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" value="Signup"  class="btn btn-block btn-success" />
		<input type="hidden" name="next" value="{{ next }}" />
	</form>
{% endblock %}

{% block javascript %}
	{{block.super}}
{% endblock %}