diaries/api/urls.py
from django.urls import path

from .import views


app_name = 'diaries_api'
urlpatterns = [
    path('', views.DiaryListCreateAPIView.as_view(), name='diary_list'),
    path(
        '<str:diary_slug>',
        views.DiaryRetrieveUpdateDestroyAPIView.as_view(),
        name='diary_detail'),
]

diaries/urls.py
from django.urls import path, include

from . import views

app_name = 'diaries'

urlpatterns = [
    path('', views.DiaryListView.as_view(), name='diary_list'),
    path(
        'popular',
        views.DiaryListView.as_view(
            order_by='popularity',
            template_name='diaries/diary_list_popular.html'
        ),
        name='popular_diary_list'),
    path(
        'discover',
        views.DiaryListView.as_view(
            order_by='discover',
            template_name='diaries/diary_list_discover.html'
        ),
        name='discover_diary_list'),
    path('diary/<str:diary_slug>/', include([
        path('', views.DiaryDetailView.as_view(), name='diary_detail'),
        path('like', views.DiaryLikeView.as_view(), name='diary_like'),
        path('update', views.DiaryUpdateView.as_view(), name='diary_update'),
        path('delete', views.DiaryDeleteView.as_view(), name='diary_delete'),
        # Comments
        path(
            'comment/create',
            views.CommentCreateView.as_view(),
            name='comment_create'
        ),
        path(
            'comment/<int:comment_id>/delete',
            views.CommentDeleteView.as_view(),
            name='comment_delete'
        ),
    ])
    ),
    path('create', views.DiaryCreateView.as_view(), name='diary_create'),
    path('search', views.SearchView.as_view(), name='search'),
    path(
        'notifications',
        views.NotificationListView.as_view(
            template_name='diaries/notification_list.html'
        ),
        name='notification_list'
    ),
]

yawm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache
import notifications.urls
from ckeditor_uploader import views as ckeditor_uploader_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'inbox/notifications/',
        include(
            notifications.urls,
            namespace='notifications')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('auth/', include('allauth.urls')),

    path('ckeditor/', include([
        path(
            'upload/',
            login_required(ckeditor_uploader_views.upload),
            name='ckeditor_upload'
        ),
        path(
            'browse/',
            login_required(never_cache(ckeditor_uploader_views.browse)),
            name='ckeditor_browse'
        ),
    ])),
    path('', include('diaries.urls', namespace='diaries')),
    # re_path(r'^api/(?P<version>(v1|v2))/', include([
    path('api/v1/', include([
        path('diaries/', include('diaries.api.urls', namespace='diaries_api'))
    ])),

]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

diaries/models.py
import bleach
from django.db import models
from django.db.models import F, Q
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.text import slugify
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from notifications.models import Notification
from notifications.signals import notify

from accounts.models import Profile
from core.utils import get_image_upload_path, generate_random_string
from .utils import delete_ckeditor_rich_text_images


class DiaryQuerySet(models.QuerySet):

    def active(self, user):
        """Returns only the diaries that user should be able to see
           If the user isn't authenticated, he should only see public diaries
           If he's authencated he can also see his private diaries
        """
        if user.is_authenticated:
            # User can see his non-visible diaries.
            qs = self.filter(
                Q(author=user.profile) |
                Q(is_visible=Diary.ALL_CHOICE))
            qs = qs.distinct()
        else:
            qs = self.filter(is_visible=Diary.ALL_CHOICE)
        qs = qs.select_related('author')
        return qs

    def by_followed_profiles(self, profile):
        """Returns diaries of followed profiles"""
        followed_profiles = profile.followed_profiles.all()
        qs = self.filter(
            author__in=followed_profiles,
            is_visible=Diary.ALL_CHOICE)
        return qs

    def popular(self):
        """Order the diaries based on number of comments and likes"""
        qs = self.annotate(
            ranking_factor=F('comments_count') + F('likes_count')
        )
        qs = qs.filter(is_visible=Diary.ALL_CHOICE).order_by('-ranking_factor')
        return qs


class Diary(models.Model):
    ALL_CHOICE = 'all'
    NO_ONE_CHOICE = 'no_one'
    VISIBILITY_CHOICES = (
        (ALL_CHOICE, 'All'),
        (NO_ONE_CHOICE, 'No One'))
    COMMENTABLE_CHOICES = (
        (ALL_CHOICE, 'All'),
        (NO_ONE_CHOICE, 'No One'))
    ANGRY_FEELING = '0'
    HAPPY_FEELING = '1'
    EXCITED_FEELING = '2'
    SAD_FEELING = '3'
    LOVE_FEELING = 'LOVE'
    SATISFIED_FEELING = 'SATISFIED'
    MAD_FEELING = 'MAD'
    TIRED_FEELING = 'TIRED'
    SURPRISED_FEELING = 'SURPRISED'
    AFRAID_FEELING = 'AFRAID'
    FEELINGS_CHOICES = (
        (ANGRY_FEELING, 'Angry'),
        (HAPPY_FEELING, 'Happy'),
        (EXCITED_FEELING, 'Excited'),
        (SAD_FEELING, 'Sad'),
        (LOVE_FEELING, 'Love'),
        (SATISFIED_FEELING, 'Satisfied'),
        (MAD_FEELING, 'Mad'),
        (TIRED_FEELING, 'Tired'),
        (SURPRISED_FEELING, 'Surprised'),
        (AFRAID_FEELING, 'Afraid'),)

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=275, blank=True, allow_unicode=True)
    content = RichTextUploadingField()
    description = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(
        upload_to=get_image_upload_path,
        null=True,
        blank=True)
    is_visible = models.CharField(
        help_text='Who can see this diary?',
        max_length=7,
        choices=VISIBILITY_CHOICES,
        default=ALL_CHOICE,
        blank=True)
    is_commentable = models.CharField(
        help_text='Who can comment on this diary?',
        choices=COMMENTABLE_CHOICES,
        max_length=7,
        default=ALL_CHOICE,
        blank=True)
    feeling = models.CharField(
        help_text='How do you feel?',
        max_length=15,
        choices=FEELINGS_CHOICES,
        null=True,
        blank=True)
    is_deleted = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    likes = models.ManyToManyField(
        Profile,
        through='DiaryLike',
        through_fields=('diary', 'user'))
    likes_count = models.PositiveIntegerField(default=0)
    comments_count = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(
        Profile,
        related_name='written_diaries',
        on_delete=models.CASCADE)

    objects = DiaryQuerySet.as_manager()

    class Meta:
        verbose_name_plural = 'diaries'
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if(not self.id):
            title_slug = slugify(self.title, allow_unicode=True)
            new_slug = '{}'.format(title_slug)

            while Diary.objects.filter(slug=new_slug).exists():
                new_slug = '{}-{}'.format(title_slug, generate_random_string())

            self.slug = new_slug

        # self.description is supposed to be plain text so that it's displayed
        # in the diary list page
        start_length = 500
        total_position = len(self.content)
        text_description = bleach.clean(
            self.content[:start_length],
            strip=True,
            tags=[],
            attributes=[]
        ).strip()
        # If 500 non-clean characters is not enough, add 50 every time
        while len(text_description) < 245 & start_length < total_position:
            text_description += bleach.clean(
                self.content[start_length:start_length + 50],
                strip=True,
                tags=[],
                attributes=[]
            ).strip()
            start_length += 50
        self.description = text_description[:255]

        return super(Diary, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            'diaries:diary_detail',
            kwargs={'diary_slug': self.slug})


@receiver(post_delete, sender=Diary)
def diary_pictures_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    delete_ckeditor_rich_text_images(instance.content)


class DiaryLike(models.Model):
    user = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='liked_diaries')
    diary = models.ForeignKey(
        Diary,
        on_delete=models.CASCADE,
        related_name='diary_likes')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['user', 'diary']

    def __str__(self):
        return '{} : {} ({})'.format(self.user, self.diary, self.created_on)


class Comment(models.Model):
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    diary = models.ForeignKey(
        Diary,
        related_name='comments',
        on_delete=models.CASCADE)
    likes = models.ManyToManyField(
        Profile,
        related_name='liked_comments',
        through='CommentLike',
        through_fields=('comment', 'user'))
    author = models.ForeignKey(
        Profile,
        related_name='written_comments',
        on_delete=models.CASCADE)

    def __str__(self):
        return '{}... ({})'.format(self.content, self.author)


class CommentLike(models.Model):
    user = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='comment_likes')
    comment = models.ForeignKey(
        Comment,
        on_delete=models.CASCADE,
        related_name='comment_likes')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} : {} ({})'.format(
            self.user,
            self.comment,
            self.created_on)


@receiver(post_save, sender=DiaryLike)
def diary_like_create_handler(sender, instance, created, **kwargs):
    if instance.user != instance.diary.author:
        notify.send(
            sender=instance.user,
            recipient=instance.diary.author.user,
            target=instance.diary,
            verb='Liked')


@receiver(post_save, sender=Comment)
def comment_create_handler(sender, instance, created, **kwargs):
    if instance.author != instance.diary.author:
        notify.send(
            sender=instance.author,
            recipient=instance.diary.author.user,
            target=instance.diary,
            verb='Commented on')


@receiver(post_delete, sender=Diary)
def delete_notifications_when_diary_is_deleted(sender, instance, **kwargs):
    qs = Notification.objects.filter(target_object_id=instance.id)
    qs.delete()

diaries/forms.py
from django import forms
from bleach.sanitizer import Cleaner

from .models import Diary, Comment


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = [
            'title',
            'content',
            'image',
            'is_visible',
            'is_commentable',
            'feeling',
        ]

    def clean_content(self):
        content = self.cleaned_data['content']
        cleaner = Cleaner(
            tags=[
                'p', 'u', 's', 'i', 'b', 'a', 'sub', 'sup', 'img', 'div',
                'ul', 'li', 'ol', 'em', 'strong', 'h1', 'h2', 'h3', 'h4',
                'h5', 'h6', 'pre', 'address', 'caption'
            ],
            attributes={
                'a': ['href', 'target'],
                'img': ['src', 'style', 'alt'],
            },
            styles=['height', 'width'],
            protocols=['http', 'https', 'mailto']
        )
        content = cleaner.clean(content)
        return content


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class SearchForm(forms.Form):
    q = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'Search query'}))
    model = forms.ChoiceField(
        label='',
        choices=(('diary', 'diaries'), ('profile', 'Profiles')),
        widget=forms.RadioSelect)

diaries/api/views.py
from rest_framework import generics
from rest_framework.pagination import PageNumberPagination
from rest_framework import permissions

from .serializers import DiaryListSerializer, DiaryDetailSerializer
from ..models import Diary


class StandardPagination(PageNumberPagination):
    page_size = 9


class IsOwnerOrReadOnly(permissions.BasePermission):
    def has_object_permission(self, request, view, obj):
        if request.method in permissions.SAFE_METHODS:
            return True
        if request.user.is_authenticated:
            if obj.author == request.user.profile:
                return True
        return False


class DiaryListCreateAPIView(generics.ListCreateAPIView):
    model = Diary
    page_size = 9
    pagination_class = StandardPagination

    def perform_create(self, serializer):
        serializer.save(author=self.request.user.profile)

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return DiaryDetailSerializer
        return DiaryListSerializer

    def get_queryset(self):
        order_by = self.request.query_params.get('order_by', None)
        if order_by == 'popularity':
            qs = self.model.objects.popular()
        elif order_by == 'discover':
            qs = self.model.objects.all()
            qs = qs.active(self.request.user)
        else:
            if self.request.user.is_authenticated:
                followed_profiles_diaries = Diary.objects\
                    .by_followed_profiles(self.request.user.profile).order_by()

                current_profile_diaries = Diary.objects.filter(
                    author=self.request.user.profile
                ).order_by()

                qs = followed_profiles_diaries.union(current_profile_diaries)
                qs = qs.order_by('-created_on')
            else:
                qs = self.model.objects.all()
        return qs


class DiaryRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    lookup_field = 'slug'
    lookup_url_kwarg = 'diary_slug'
    permission_classes = [IsOwnerOrReadOnly]
    serializer_class = DiaryDetailSerializer

    def get_queryset(self):
        qs = Diary.objects.active(self.request.user)
        return qs

diaries/templates/diaries/base_diaries.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{block.super}}{% endblock %}

{% block stylesheet %}
	{{block.super}}
	<link rel="stylesheet" type="text/css" href="{% static 'core/css/main.css' %}">
{% endblock %}

{% block body %}
	{{block.super}}
	<div class="container">
		{% block content %}{% endblock %}
	</div>
	<script type="text/javascript" src="{% static 'core/js/main.js' %}"></script>
{% endblock %}
{% block javascript %}
	{{block.super}}
{% endblock %}

diaries/templates/diaries/comment_delete.html
{% extends 'diaries/base_diaries.html' %}

{% block title %}Delete comment - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

	{% block content %}
		<div class="text-center">
			<h2>Are sure you want to delete this comment:</h2>
			<p>{{ comment.content }}</p>
			<p>on: <a href="{{ comment.diary.get_absolute_url }}">{{ comment.diary.title }}</a></p>
			<form method="post" action="{% url 'diaries:comment_delete' comment.diary.slug comment.id %}">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="btn btn-danger">Delete</button>
			</form>
				<a href="{% url 'diaries:diary_detail' comment.diary.slug %}"><button class="btn btn-success mt-2">Cancel</button></a>
		</div>
	{% endblock %}

diaries/templates/diaries/diary_create.html
{% extends 'diaries/base_diaries.html' %}
{% block title %}Create a new diary - {{block.super}}{% endblock %}
	{% block stylesheet %}
		{{ block.super }}
	{% endblock %}
	{% block content %}
		<div>
			<h2>Create a new diary:</h2>
			<form method="post" action="{% url 'diaries:diary_create' %}" enctype="multipart/form-data" class="browser-default">
				{% csrf_token %}
				{% include 'core/snippets/form_fields.html' with form=form %}
				<button type="submit" class="btn btn-block btn-success">Create</button>
			</form>
		</div>
	{% endblock %}
	{% block javascript %}
		{{ block.super }}
	{% endblock %}

diaries/templates/diaries/diary_delete.html
{% extends 'diaries/base_diaries.html' %}

{% block title %}Delete diary - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

	{% block content %}
		<div class="text-center">
			<h2>Are sure you want to delete this diary</h2>
			{% if diary.image %}
				<img src="{{ diary.image.url }}" class="img-fluid" style="max-height: 400px;">
			{% endif %}
			<h3>{{ diary.title }}</h3>
			<form method="post" action="{% url 'diaries:diary_delete' diary.slug %}">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" class="btn btn-danger">Delete</button>
			</form>
				<a href="{% url 'diaries:diary_detail' diary.slug %}"><button class="btn btn-success mt-2">Cancel</button></a>
		</div>
	{% endblock %}

diaries/templates/diaries/diary_detail.html
{% extends 'diaries/base_diaries.html' %}
{% load thumbnail %}

{% block title %}{{ diary.title }} - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

	{% block content %}
		<div>
			{% if diary.is_visible == 'no_one' %}
			<div class="alert alert-warning alert-dismissible">
				No one other than you can see this diary.
				<a class="close" data-dismiss="alert" >&times;</a>
			</div>
			{% endif %}
			{% if diary.image %}
			<div>
				<img src="{{ diary.image.url }}" class="img-fluid mx-auto d-block">
			</div>
			{% endif %}
			{% if request.user.profile == diary.author %}
				<p class="float-right mt-2">
					<a href="{% url 'diaries:diary_update' diary.slug %}" class="btn btn-info">
						<span class="oi" data-glyph="pencil" title="pencil" aria-hidden="true"></span>
					</a>
					<a href="{% url 'diaries:diary_delete' diary.slug %}" class="btn btn-danger">
						<span class="oi" data-glyph="trash" title="trash" aria-hidden="true"></span>
					</a>
				</p>
			{% endif %}
			<h1 class="text-center">{{ diary.title }}</h1>
			<div class="row">
				<div class="col-sm-10">
					<div class="media">
						<a href="{{ diary.author.get_absolute_url }}">
							<img src="{% thumbnail diary.author.image '50x50' crop='center' as img %}{{ img.url }}{% endthumbnail %}" class="img-fluid rounded-circle author-metadata-image d-block mt-2">
						</a>
							<div class="media-body ml-2">
								<h3>
									<a href="{{ diary.author.get_absolute_url }}">{{ diary.author }}</a>
									{% if diary.feeling %}
									<small class="text-secondary">({{ diary.get_feeling_display }})</small>
									{% endif %}
								</h3>
								<p>Published <b>{{ diary.created_on|timesince }}</b> ago | On: <b>{{ diary.created_on|date:'DATE_FORMAT' }}</b></p>
							</div>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="dropdown">
						<button class="btn btn-body dropdown-toggle" data-toggle="dropdown">
							<span class="oi" data-glyph="fork" title="fork" aria-hidden="true"></span>
						</button>
						<div class="dropdown-menu">
							<div class="dropdown-header">Share this diary</div>
							<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri  }}&title={{ diary.title|iriencode }}" class="dropdown-item" target="_blank" rel="nofollow">facebook</a>
							<a href="#!" class="dropdown-item">twitter</a>
						</div>
					</div>
				</div>
			</div>
			<br>
			<div>
				{{ diary.content|safe }}
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col text-center offset-s3">
				<span>
					<form action="{% url 'diaries:diary_like' diary.slug %}" method="post" id="like-form">
						{% csrf_token %}
						<button type="submit" class="btn btn-body">
						{% if request.user.profile in diary.likes.all %}
							<span class="oi text-danger" data-glyph="heart" title="heart" aria-hidden="true"></span>
						{% else %}
							<span class="oi" data-glyph="heart" title="heart" aria-hidden="true"></span>
						{% endif %}
							 ({{ diary.likes_count }})
						</button>
					</form>
				</span>
						
			</div>
			<div class="col text-center">
				<span class="ml-5">
					<span class="oi" data-glyph="comment-square" title="comment square" aria-hidden="true"></span>
					({{ diary.comments_count }})
				</span>
			</div>
			<div class="col text-center">
				<div class="dropdown">
					<button class="btn btn-body dropdown-toggle" data-toggle="dropdown">
						<span class="oi" data-glyph="fork" title="fork" aria-hidden="true"></span>
					</button>
					<div class="dropdown-menu">
						<div class="dropdown-header">Share this diary</div>
						<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri  }}&title={{ diary.title|iriencode }}" class="dropdown-item" target="_blank" rel="nofollow">facebook</a>
						<a href="#!" class="dropdown-item">twitter</a>
					</div>
				</div>
			</div>
		</div>
		<!-- Comment Section Begins -->
		<h3>Comments:</h3>
		<div>
			{% for comment in diary.comments.all %}
			<div class="media mt-3 jumbotron p-1 mt-1">
				<img src="{% thumbnail comment.author.image '50x50' crop='center' as img %}{{ img.url }}{% endthumbnail %}" class="img-fluid rounded-circle author-metadata-image mt-2">
				<div class="media-body ml-2">
					<h4 class="d-inline-block mr-3"><a href="{{ comment.author.get_absolute_url }}">{{ comment.author }}</a></h4>
					<small class="d-inline-block mr-3">{{ comment.created_on|timesince }} ago</small>
					{% if request.user.profile == comment.author %}
					<span class="right">
						<a href="{% url 'diaries:comment_delete' diary.slug comment.id %}">
							<span class="oi" data-glyph="trash" title="trash" aria-hidden="true"></span>
						</a>
					</span>
					{% endif %}
					<p>{{ comment.content|linebreaksbr }}</p>
				</div>
			</div>
			{% endfor %}
		<!-- Comment Section Ends -->
		<!-- Comment Form Section Begins -->
		{% if comment_form %}
			{% if request.user.is_authenticated %}
				<div class="mb-4">
					<form method="post" action="{% url 'diaries:comment_create' diary.slug %}">
						{% csrf_token %}
						{% include 'core/snippets/form_fields.html' with form=comment_form %}
						<button type="submit" class="btn btn-success btn-block">Comment</button>
					</form>
				</div>
			{% else %}
				<p>Please <a href="{% url 'account_login' %}?next={{ request.path }}">login</a> to comment.</p>
			{% endif %}
		{% else %}
			<p>Comments are disabled for this diary.</p>
		{% endif %}
		<!-- Comment Form Section Ends -->
	{% endblock %}

diaries/templates/diaries/diary_list.html
{% extends 'diaries/base_diaries.html' %}
{% load static %}

{% block title %}Recent Diaries From Your Circle - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

{% block content %}
	<h3>Recent Diaries From Your Circle:</h3>
	{% include 'diaries/snippets/diary_list_snippet.html' with diaries=diaries %}
{% endblock %}

diaries/templates/diaries/diary_list_discover.html
{% extends 'diaries/base_diaries.html' %}
{% load static %}

{% block title %}Recent Diaries - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

{% block content %}
	<h3>Recent Diaries:</h3>
	{% include 'diaries/snippets/diary_list_snippet.html' with diaries=diaries %}
{% endblock %}

diaries/templates/diaries/diary_list_popular.html
{% extends 'diaries/base_diaries.html' %}
{% load static %}

{% block title %}Popular Diaries - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

{% block content %}
	<h3>Popular Diaries:</h3>
	{% include 'diaries/snippets/diary_list_snippet.html' with diaries=diaries %}
{% endblock %}

diaries/templates/diaries/diary_update.html
{% extends 'diaries/base_diaries.html' %}

{% block title %}Update diary - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

	{% block content %}
		<div>
			<h2>Update a diary</h2>
			<h3>{{ diary.title }}</h3>
			<form method="post" action="{% url 'diaries:diary_update' diary.slug %}" enctype="multipart/form-data">
				{% csrf_token %}
				{% include 'core/snippets/form_fields.html' with form=form %}
				<button type="submit" class="btn btn-block btn-success">Update</button>
			</form>
		</div>
	{% endblock %}

diaries/templates/diaries/notification_list.html
{% extends 'diaries/base_diaries.html' %}
{% load static %}
{% load notifications_tags %}

{% block title %}Recent Notifications - {{block.super}}{% endblock %}

{% block head %}{{block.super}}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12 mb-2">
      You have <b>{% notifications_unread %}</b> unread notifications.
      <a href="{% url 'notifications:mark_all_as_read' %}?next={{ request.path }}">Mark all as read</a>
    </div>
    {% for n in notifications %}
      {% if n.unread  %}
      <div class="col-12 mt-1" style="background-color: #DEDEDE;">
      {% else %}
      <div class="col-12 mt-1">
      {% endif %}
        <p>
          <img src="{% if n.actor.image %}{{ n.actor.image.url }}{% else %}{% static 'img/default_person_image.png' %}{% endif%}" class="img-fluid rounded-circle" style="height: 30px; width: 30px;">
          <a href="{{ n.actor.get_absolute_url }}">{{ n.actor }}</a> <b>{{ n.verb }}</b>
          <a href="{{ n.target.get_absolute_url }}">{{ n.target }}</a>
          <b>{{ n.timestamp|timesince }} ago</b>

      {% if n.unread  %}
        <a href="{% url 'notifications:mark_as_read' slug=n.slug %}?next={{ request.path }}">
          <span class="oi" data-glyph="action-redo" title="Mark as read" aria-hidden="tru"></span>
        </a>
      {% else %}
        <a href="{% url 'notifications:mark_as_unread' slug=n.slug %}?next={{ request.path }}">
          <span class="oi" data-glyph="action-undo" title="Mark as unread" aria-hidden="tru"></span>
        </a>
      {% endif %}
          
          
        </p>
      </div>
    {% empty %}
      <span>You are up to date.</span>
    {% endfor %}
</div>
<div class="row">
  <!-- Pagination Start -->
  <div class="col-md-12">
    {% if is_paginated %}
      <ul class="pagination justify-content-center">
        <li class=" page-item {% if not page_obj.has_previous %}disabled{% endif %}">
          <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %} class="page-link">&lt;</a>
        </li>
        {% for page in page_obj.paginator.page_range %}
          <li  class="page-item {% if page == page_obj.number %}active{% endif %}">
            <a href="?page={{ page }}" class="page-link">{{ page }}</a>
          </li>
        {% endfor %}
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
          <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %} class="page-link">&gt;</a>
        </li>
      </ul>
    {% endif %}
  </div>
  <!-- Pagination End -->
</div>
{% endblock %}