accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('profiles', views.ProfileTopListView.as_view(), name='profile_list'),
    path('<str:username>/', include([
         path(
             '',
             views.ProfileDetailView.as_view(),
             name='profile_detail'),
         path(
             'update',
             views.ProfileUpdateView.as_view(),
             name='profile_update'),
         path(
             'follow',
             views.ProfileFollowView.as_view(),
             name='profile_follow'),
         path(
             'followers',
             views.ProfileFollowersListView.as_view(),
             name='profile_followers_list'),
         path(
             'following',
             views.ProfileFollowingListView.as_view(),
             name='profile_following_list')]))
]

diaries/urls.py
from django.urls import path, include

from . import views

app_name = 'diaries'

urlpatterns = [
    path('', views.DiaryListView.as_view(), name='diary_list'),
    path(
        'popular',
        views.DiaryListView.as_view(
            order_by='popularity',
            template_name='diaries/diary_list_popular.html'
        ),
        name='popular_diary_list'),
    path(
        'discover',
        views.DiaryListView.as_view(
            order_by='discover',
            template_name='diaries/diary_list_discover.html'
        ),
        name='discover_diary_list'),
    path('diary/<str:diary_slug>/', include([
        path('', views.DiaryDetailView.as_view(), name='diary_detail'),
        path('like', views.DiaryLikeView.as_view(), name='diary_like'),
        path('update', views.DiaryUpdateView.as_view(), name='diary_update'),
        path('delete', views.DiaryDeleteView.as_view(), name='diary_delete'),
        # Comments
        path(
            'comment/create',
            views.CommentCreateView.as_view(),
            name='comment_create'
        ),
        path(
            'comment/<int:comment_id>/delete',
            views.CommentDeleteView.as_view(),
            name='comment_delete'
        ),
    ])
    ),
    path('create', views.DiaryCreateView.as_view(), name='diary_create'),
    path('search', views.SearchView.as_view(), name='search'),
    path(
        'notifications',
        views.NotificationListView.as_view(
            template_name='diaries/notification_list.html'
        ),
        name='notification_list'
    ),
]

yawm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache
import notifications.urls
from ckeditor_uploader import views as ckeditor_uploader_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'inbox/notifications/',
        include(
            notifications.urls,
            namespace='notifications')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('auth/', include('allauth.urls')),

    path('ckeditor/', include([
        path(
            'upload/',
            login_required(ckeditor_uploader_views.upload),
            name='ckeditor_upload'
        ),
        path(
            'browse/',
            login_required(never_cache(ckeditor_uploader_views.browse)),
            name='ckeditor_browse'
        ),
    ])),
    path('', include('diaries.urls', namespace='diaries')),
    # re_path(r'^api/(?P<version>(v1|v2))/', include([
    path('api/v1/', include([
        path('diaries/', include('diaries.api.urls', namespace='diaries_api'))
    ])),

]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

diaries/forms.py
from django import forms
from bleach.sanitizer import Cleaner

from .models import Diary, Comment


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = [
            'title',
            'content',
            'image',
            'is_visible',
            'is_commentable',
            'feeling',
        ]

    def clean_content(self):
        content = self.cleaned_data['content']
        cleaner = Cleaner(
            tags=[
                'p', 'u', 's', 'i', 'b', 'a', 'sub', 'sup', 'img', 'div',
                'ul', 'li', 'ol', 'em', 'strong', 'h1', 'h2', 'h3', 'h4',
                'h5', 'h6', 'pre', 'address', 'caption'
            ],
            attributes={
                'a': ['href', 'target'],
                'img': ['src', 'style', 'alt'],
            },
            styles=['height', 'width'],
            protocols=['http', 'https', 'mailto']
        )
        content = cleaner.clean(content)
        return content


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class SearchForm(forms.Form):
    q = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': 'Search query'}))
    model = forms.ChoiceField(
        label='',
        choices=(('diary', 'diaries'), ('profile', 'Profiles')),
        widget=forms.RadioSelect)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load notifications_tags %}
{% load thumbnail %}
<head>
	<title>{% block title %}MyDay{% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="widt=device-width, initial-scale=1">
	{% block stylesheet %}
	<link rel="stylesheet" type="text/css" href="{% static 'core/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/open-iconic.min.css' %}">
	{% endblock %}
</head>
<body>
	{% block body %}
	<div class="container">
		<div class="row mt-2">
			{% for message in messages %}
			<div class="col-12">
				<div class="alert alert-dismissible {{ message.tags }}">
					{{ message }}
					<a class="close" data-dismiss='alert'>&times;</a>
				</div>
			</div>
			{% endfor %}
		</div>
		<div class="row">
			<div class="col-12">
				<nav class="navbar navbar-expand-sm">
					<a class="navbar-brand" href="{% url 'diaries:diary_list' %}">Diaries</a>
					<button class="navbar-toggler" data-toggle="collapse" data-target="#TopNavabar">
						<span class="navbar-toggler-icon oi" data-glyph="menu" title="menu" aria-hidden="true"></span>
					</button>
					<form class="form form-inline ml-2 mt-2" action="{% url 'diaries:search' %}">
					    <div class="input-group">
					        <div class="input-group-append">
					        <div id="div_id_q" class="form-group">
					            <div class="">
					                <input type="text" name="q" placeholder="Search query" class="textinput textInput form-control" required id="id_q" value="{{ q }}">
					            </div>
					        </div>
					        <div id="div_id_model" class="form-group">
					            <div class="ml-2">
					                <div class="form-check">
					                    <label for="id_id_model_0_1" class="form-check-label">
					                        <input type="radio" class="form-check-input" checked="checked" name="model" id="id_id_model_0_1" value="diary" >
					                        diaries
					                    </label>
					                </div>
					                <div class="form-check">
					                    <label for="id_id_model_0_2" class="form-check-label">
					                        <input type="radio" class="form-check-input" name="model" id="id_id_model_0_2" value="profile" >
					                        Profiles
					                        </label>
					                </div>
					            </div>
					        </div>
					            <button class="btn btn-body">
					                <span class="oi" data-glyph="magnifying-glass" title="Search" aria-hidden="true"></span>
					            </button>
					        </div>
					    </div>
					</form>
					<div class="collapse navbar-collapse" id="TopNavabar">
						<ul class="navbar-nav" style="margin-left: auto;">
							{% if request.user.is_authenticated %}
								<li class="nav-item ml-2">
									<a class="nav-link" href="{% url 'diaries:diary_create' %}">Write a new diary <span class="oi" data-glyph="pencil" title="Write a new diary" aria-hidden="true"></span></a>
								</li>
								<li class="nav-item ml-2">
									<a class="nav-link" href="{% url 'accounts:profile_list' %}">Interesting People <span class="oi" data-glyph="people" title="Interesting People" aria-hidden="true"></span></a>
								</li>
								<li class="nav-item ml-2">
									{% with notifications=request.user.notifications.all|slice:":7" %}
									<div class="dropdown">
										<button class="btn dropdown-toggle" data-toggle="dropdown">
											<span class="oi" data-glyph="bell" title="Notifications" aria-hidden="true"></span>
											{% if notifications %}
												<span class="badge badge-info">{% notifications_unread %}</span>
											{% endif %}
										</button>
										<div class="dropdown-menu dropdown-menu-right w-2" style="font-size: small;padding-right: 15px;">
											<div class="dropdown-header">
												You have <b>{% notifications_unread %}</b> unread notifications.
												<a href="{% url 'notifications:mark_all_as_read' %}?next={{ request.path }}">Mark all as read</a>
											</div>
											{% for n in notifications %}
												{% if n.unread  %}
												<div class="dropdown-item mt-1" style="background-color: #DEDEDE;">
												{% else %}
												<div class="dropdown-item mt-1">
												{% endif %}
													<p style="font-size: 12px;">
														<img src="{% thumbnail n.actor.image '50x50' crop='center' as img %}{{ img.url }}{% endthumbnail %}" class="img-fluid rounded-circle" style="height: 30px; width: 30px;">
														<a href="{{ n.actor.get_absolute_url }}">{{ n.actor }}</a> <b>{{ n.verb }}</b>
														{% if n.target %}
														<a href="{{ n.target.get_absolute_url }}">{{ n.target }}</a>
														{% endif %}

												{% if n.unread  %}
													<a href="{% url 'notifications:mark_as_read' slug=n.slug %}?next={{ request.path }}">
														<span class="oi" data-glyph="action-redo" title="Mark as read" aria-hidden="tru"></span>
													</a>
												{% else %}
													<a href="{% url 'notifications:mark_as_unread' slug=n.slug %}?next={{ request.path }}">
														<span class="oi" data-glyph="action-undo" title="Mark as unread" aria-hidden="tru"></span>
													</a>
												{% endif %}
														<br>
														<i class="d-inline-block" style="margin-left: 35px;">{{ n.timestamp|timesince }} ago</i>
													</p>
												</div>
											{% empty %}
												<span class="dropdown-item-text">You are up to date.</span>
											{% endfor %}
											<div  class="dropdown-item text-center">
												<a href="{% url 'diaries:notification_list' %}">Show all notifications</a>
											</div>
										</div>
									</div>
									{% endwith %}
								</li>
								<li class="nav-item">
									<div class="dropdown">
										{% with profile=request.user.profile %}
										<img src="{% thumbnail profile.image '50x50' crop='center' as img %}{{ img.url }}{% endthumbnail %}" class="img-fluid dropdown-toggle rounded-circle" data-toggle="dropdown" width="80%">
										<div class="dropdown-menu">
											<a href="{{ profile.get_absolute_url }}" class="dropdown-item">
												My Profile ({{ request.user.username }}) 
												<span class="oi" data-glyph="person" title="My Profile" aria-hidden="true"></span>
											</a>	
											<a href="{% url 'accounts:profile_update' request.user.username %}" class="dropdown-item">
												Update Profile 
												<span class="oi" data-glyph="pencil" title="Update profile" aria-hidden="true"></span>
											</a>
											<a href="{% url 'account_logout' %}" class="dropdown-item">
												Logout 
												<span class="oi" data-glyph="account-logout" title="Logout" aria-hidden="true"></span>
											</a>	
										</div>
										{% endwith %}
									</div>
								</li>
							{% else %}
								<li class="nav-item">
									<a class="nav-link" href="{% url 'account_login' %}">
										Login
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{% url 'account_signup' %}">
										Signup
									</a>
								</li>
							{% endif %}
						</ul>
					</div>
				</nav>
			</div>
		</div>
		<div class="row my-5">
			<div class="col-12">
				<ul class="nav justify-content-center">
					<li class="nav-item"><a class="nav-link" href="{% url 'diaries:diary_list' %}">Recent <span class="oi" data-glyph="bolt" title="Diaries from my circle" aria-hidden="true"></span></a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'diaries:popular_diary_list' %}">Popular <span class="oi" data-glyph="fire" title="Popular diaries" aria-hidden="true"></span></span></a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'diaries:discover_diary_list' %}">Discover <span class="oi" data-glyph="compass" title="Newest diaries" aria-hidden="true"></span></a></li>
					<li class="nav-item"><a class="nav-link disabled" href="#!">WeekBest <span class="oi" data-glyph="graph" title="graph" aria-hidden="true"></span></a></li>
				</ul>
			</div>
		</div>
	</div>
	{% endblock %}
	{% block javascript %}
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'core/js/main.js' %}"></script>
	{% endblock %}
</body>
</html>